baseURL: "https://givemoneyto.me/"
title: "Give money to me"

staticDir: static/build
assetDir: static/build

disableKinds:
  - sitemap
  - taxonomyTerm
  - 404

outputs:
  home:
    - html
  page:
    - html
